fix: remove unsupported orderby from Teams polling query
Microsoft Graph API does not support orderby on chat messages.
Error: QueryOptions to order by 'CreatedDateTime' in 'Ascending' direction is not supported.